version: "3.9"
services:
  db:
    container_name: postgresql-backend
    image: postgres
    restart: always
    volumes:
      - db-data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    profiles: ["local"]
volumes:
  db-data:
